<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>a2f2a096-7b33-4884-abc4-bed0c33a19e6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
        <PackageReference Include="Wodsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskFlow.Application\TaskFlow.Application.csproj" />
      <ProjectReference Include="..\TaskFlow.Infrastructure\TaskFlow.Infrastructure.csproj" />
    </ItemGroup>

</Project>
